services:
  - name: web
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn modelsite.wsgi --log-file -
    env:
      - key: SECRET_KEY
        # Ссылка на переменную SECRET_KEY из .env
        file: .env
        variable: SECRET_KEY
      - key: DEBUG
        # Ссылка на переменную DEBUG из .env
        file: .env
        variable: DEBUG
      - key: ALLOWED_HOSTS
        # Укажите здесь адрес вашего сайта, например, https://react-topmodel.onrender.com/
        value: ".onrender.com"
    envVars:
      - key: PYTHONPATH
        value: "/app/modelsite"