# Generated by Django 5.0.4 on 2024-04-09 16:22

import django.core.validators
import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_alter_model_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='avatar',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[500, 500], upload_to='avatars/', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='model',
            name='experience',
            field=models.PositiveIntegerField(help_text='example: 2010', validators=[django.core.validators.MinValueValidator(1980), django.core.validators.MaxValueValidator(2024)], verbose_name='Experience'),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, default=None, null=True, upload_to='photos/', verbose_name='Photo')),
                ('small_img', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[1920, 1080], upload_to='photos/small/', verbose_name='Small Photo')),
                ('middle_img', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[1920, 1080], upload_to='photos/middle/', verbose_name='Middle Photo')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Register Date')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Date of update')),
                ('is_published', models.BooleanField(default=True, verbose_name='Published')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='model.model')),
            ],
        ),
    ]
