# Generated by Django 5.0.4 on 2024-04-09 20:00

import django.core.validators
import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0003_alter_model_avatar_alter_model_experience_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='model',
            options={'verbose_name': 'Model', 'verbose_name_plural': 'Models'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'Photo', 'verbose_name_plural': 'Photos'},
        ),
        migrations.AlterField(
            model_name='model',
            name='experience',
            field=models.PositiveIntegerField(help_text='example: 2010', validators=[django.core.validators.MinValueValidator(1980), django.core.validators.MaxValueValidator(2024)], verbose_name='Experience since'),
        ),
        migrations.AlterField(
            model_name='model',
            name='past_clients',
            field=models.TextField(blank=True, help_text='comma separated enumeration. example: client1, client2, client3...', verbose_name='Past clients'),
        ),
        migrations.AlterField(
            model_name='model',
            name='top_model',
            field=models.BooleanField(default=False, verbose_name='Top model'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='img',
            field=django_resized.forms.ResizedImageField(crop=None, default=None, force_format='JPEG', keep_meta=True, null=True, quality=-1, scale=None, size=None, upload_to='photos/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='middle_img',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=-1, scale=None, size=[1080, 1080], upload_to='photos/middle/', verbose_name='Middle Photo'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.model'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='small_img',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=-1, scale=None, size=[300, 300], upload_to='photos/small/', verbose_name='Small Photo'),
        ),
    ]
