# Generated by Django 5.0.4 on 2024-04-09 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0004_alter_model_options_alter_photo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='model',
            managers=[
            ],
        ),
    ]
