# Generated by Django 5.0.4 on 2024-04-09 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0005_alter_model_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='facebook',
            field=models.URLField(blank=True, help_text='example: https://facebook.com/myname', max_length=100, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='model',
            name='instagram',
            field=models.URLField(blank=True, help_text='example: https://instagram.com/myname', max_length=100, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='model',
            name='telegram',
            field=models.URLField(blank=True, help_text='example: https://telegram.com/myname', max_length=100, verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='model',
            name='vk',
            field=models.URLField(blank=True, help_text='example: https://vk.com/myname', max_length=100, verbose_name='VK'),
        ),
    ]
