# Generated by Django 5.0.4 on 2024-04-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0006_alter_model_facebook_alter_model_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='birthday',
            field=models.DateField(blank=True, default='2010-01-01', help_text='YYYY-mm-dd', verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='model',
            name='email',
            field=models.EmailField(blank=True, max_length=100, verbose_name='Email'),
        ),
    ]
