# Generated by Django 5.0.4 on 2024-04-10 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0007_model_birthday_model_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='birthday',
            field=models.DateField(help_text='YYYY-mm-dd', verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='model',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='Email'),
        ),
    ]
