# Generated by Django 5.0.4 on 2024-04-11 19:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0009_model_followers_model_size_alter_model_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='followers',
            field=models.SmallIntegerField(help_text='Example: write "9" if you have 9K', verbose_name='Count of followers in Instagram'),
        ),
        migrations.AlterField(
            model_name='model',
            name='size',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(100)], verbose_name='Clothing size'),
        ),
    ]
