# Generated by Django 5.0.4 on 2024-04-15 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0010_alter_model_followers_alter_model_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='followers',
            field=models.SmallIntegerField(help_text='Example: write "9" if you have 9K', verbose_name='Count K of followers in Instagram'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photographs', to='model.model'),
        ),
    ]
