# Generated by Django 5.0.4 on 2024-04-15 20:11

import django.core.validators
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', django_resized.forms.ResizedImageField(blank=True, crop=None, default=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[150, 150], upload_to='testimonials', verbose_name='Avatar')),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Name')),
                ('position', models.CharField(max_length=50, verbose_name='Position')),
                ('text', models.TextField(max_length=1000, verbose_name='Message')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Register Date')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Date of update')),
            ],
        ),
    ]
